/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ide;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author croisebeck
 */
public class PreLangWindow extends javax.swing.JFrame {

    private File arquivoAberto = null;
    
    
    /**
     * Creates new form PreLangWindow
     */
    public PreLangWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centro = new javax.swing.JPanel();
        editorScrollPane = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextArea();
        console = new javax.swing.JPanel();
        status = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();
        btnRodar = new javax.swing.JButton();
        consoleScrollPane = new javax.swing.JScrollPane();
        consoleContent = new javax.swing.JTextArea();
        menu = new javax.swing.JMenuBar();
        arquivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        salvar = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PreLang IDE");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        centro.setLayout(new java.awt.BorderLayout());

        editorScrollPane.setBackground(new java.awt.Color(51, 51, 51));

        editor.setBackground(new java.awt.Color(127, 130, 141));
        editor.setColumns(20);
        editor.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        editor.setForeground(new java.awt.Color(10, 20, 25));
        editor.setRows(5);
        editor.setTabSize(2);
        editor.setCaretColor(new java.awt.Color(255, 255, 255));
        editor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editor.setDisabledTextColor(new java.awt.Color(238, 238, 238));
        editor.setInheritsPopupMenu(true);
        editor.setMargin(new java.awt.Insets(10, 10, 10, 10));
        editorScrollPane.setViewportView(editor);

        centro.add(editorScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        console.setLayout(new java.awt.BorderLayout());

        status.setBackground(java.awt.Color.darkGray);
        status.setLayout(new java.awt.BorderLayout());

        labelStatus.setBackground(new java.awt.Color(151, 149, 149));
        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("Output");
        labelStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        status.add(labelStatus, java.awt.BorderLayout.CENTER);

        btnRodar.setForeground(new java.awt.Color(18, 47, 60));
        btnRodar.setText("Run");
        btnRodar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRodarActionPerformed(evt);
            }
        });
        status.add(btnRodar, java.awt.BorderLayout.EAST);

        console.add(status, java.awt.BorderLayout.NORTH);

        consoleContent.setBackground(java.awt.Color.white);
        consoleContent.setColumns(20);
        consoleContent.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        consoleContent.setForeground(new java.awt.Color(167, 45, 64));
        consoleContent.setRows(7);
        consoleContent.setCaretColor(new java.awt.Color(255, 255, 255));
        consoleContent.setMargin(new java.awt.Insets(10, 10, 10, 10));
        consoleScrollPane.setViewportView(consoleContent);

        console.add(consoleScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(console, java.awt.BorderLayout.SOUTH);

        menu.setBackground(java.awt.Color.darkGray);
        menu.setForeground(java.awt.Color.darkGray);
        menu.setBorderPainted(false);

        arquivo.setBackground(new java.awt.Color(0, 0, 0));
        arquivo.setForeground(new java.awt.Color(255, 255, 255));
        arquivo.setText("Arquivo");

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        arquivo.add(abrir);

        salvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        arquivo.add(salvar);

        sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        arquivo.add(sair);

        menu.add(arquivo);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setArquivoAberto(File arquivo){
        arquivoAberto = arquivo;
        this.setTitle("PreLang - "+arquivoAberto.getAbsolutePath());
    }
    
    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home"));
        fileChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) return true;
                return f.getName().endsWith(".txt");
            }

            @Override public String getDescription() { return "Arquivos PreLang"; }
        });
        fileChooser.showOpenDialog(this);
        File file = fileChooser.getSelectedFile();
        try {
            InputStream fis = new FileInputStream(file);
            fis = new BufferedInputStream(fis);
            int l;
            String content = "";
            while ( (l = fis.read()) != -1 ){
                content += (char) l;
            }
            fis.close();
            editor.setText(content);
            setArquivoAberto(file);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PreLangWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PreLangWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void btnRodarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRodarActionPerformed
        
       
        
    }//GEN-LAST:event_btnRodarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if (arquivoAberto == null){
            JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home"));
            fileChooser.setFileFilter(new FileFilter() {
                @Override
                public boolean accept(File f) {
                    if (f.isDirectory()) return true;
                    return f.getName().endsWith(".plg");
                }

                @Override public String getDescription() { return "Arquivos PreLang"; }
            });
            fileChooser.showSaveDialog(this);
            setArquivoAberto(fileChooser.getSelectedFile());
        }
        try {
            OutputStream fos = new FileOutputStream(arquivoAberto);
            fos = new BufferedOutputStream(fos);
            String text = editor.getText();
            for (int i = 0; i < text.length(); ++i){
                fos.write(text.charAt(i));
            }
            fos.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PreLangWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PreLangWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreLangWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreLangWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreLangWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreLangWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreLangWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JMenu arquivo;
    private javax.swing.JButton btnRodar;
    private javax.swing.JPanel centro;
    private javax.swing.JPanel console;
    private javax.swing.JTextArea consoleContent;
    private javax.swing.JScrollPane consoleScrollPane;
    private javax.swing.JTextArea editor;
    private javax.swing.JScrollPane editorScrollPane;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem salvar;
    private javax.swing.JPanel status;
    // End of variables declaration//GEN-END:variables
}
